### PR TITLE
Ehcache was **reporting** MappingCount as a counter instead of a gauge

### PR DESCRIPTION
**Pull request by mathieucarbou**
If someone can merge this m&m bugfix. 
Thanks :-)

### CODE REVIEW

**Comment by anthonydahanne** [comment]
@mathieucarbou this was found because after eviction it kept going up, right ? Can you please add a test that shows you fixed the behavior of MappingCount ?
Also I thought you or @henri-tremblay woudl add an issue for that as well ?

**Comment by henri-tremblay** [comment]
But I agree with @anthonydahanne that a test would be nice. And you need to rebase.

**Comment by mathieucarbou** [comment]
wow guys ;-) this PR has nothing to do with the other opened defect;-) this is just a PR fixing the statistic types ;-)

**Comment by henri-tremblay** [comment]
I know. But it still have no tests :-)

**Comment by mathieucarbou** [comment]
There are 2 tests in my PR @henri-tremblay !

**Comment by henri-tremblay** [comment]
I meant a test that is showing the number going up and down instead of ever increasing.

**Comment by mathieucarbou** [comment]
@henri-tremblay : the PR does not modify the behaviour of the stat. It modifies how the stat is described in M&M (stats descriptors) and this is tested in 2 tests, that you see in the PR.

**Comment by anthonydahanne** [comment]
@henri-tremblay  : @mathieucarbou  and I just discussed that : he explained to me the tagging as GAUGE of the stats is only for MnM and has no incidence on ehcache3 stat. That's why he's only testing the tagging.

**Comment by henri-tremblay** [comment]
Cool

**Pull request merged**
