### PR TITLE
Compat' with terracotta-management 2.4.0

### PR DESCRIPTION
**Pull request by mathieucarbou**
(moved model classes into a specific model package)

__DEPENDS ON__  https://github.com/Terracotta-OSS/terracotta-management/pull/22

### CODE REVIEW

**Comment by anthonydahanne** [comment]
it should pass now
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
@anthonydahanne : we first need to release version 2.4.0 ;-)

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
I would rather this waited till after 3.0.0 release.

**Comment by mathieucarbou** [comment]
@ljacomet : 3.0.0 will include the management module ? I hope not, because when we will do stats user stories soon, there will be some big changes in this module... The api (now moved in management-registry module) is finished, but the implementation of providers in ehcache will change a lot I think... 
Just wanted to make sure you are aware of that ?

**Comment by ljacomet** [comment]
@mathieucarbou It will be released since it is an Ehcache standalone module. However, it is no longer part of the ehcache.jar file.
Since it provides only an SPI, which we can change between 3.0 and 3.1, that will not be an issue.

**Comment by mathieucarbou** [comment]
@ljacomet : cool :-) I saw the decoupling but wasn't sure about the plan.

**Comment by mathieucarbou** [comment]
@anthonydahanne : when we'll be able to merge after 3.0.0, we'll have to make sure it is correctly rebased also.

**Comment by mathieucarbou** [comment]
@anthonydahanne : rebased!

**Comment by anthonydahanne** [comment]
sorry @mathieucarbou apparently master has moved forward... could you please rebase again ?

**Comment by mathieucarbou** [comment]
@anthonydahanne : rebased! again... ;-)

**Pull request merged**
