### PR TITLE
Issue 1079 ConcurrentWeakIdentityHashMap may get null value for mutable Key

### PR DESCRIPTION
**Pull request by zhanhb**
The hash code should be System.identityHashCode, detail http://hg.openjdk.java.net/jdk9/dev/jdk/file/d27a73776c05/src/java.base/share/classes/java/util/IdentityHashMap.java

### CODE REVIEW

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by ljacomet** [comment]
Hello,

Thanks for this PR.
Before accepting it, we need you to sign a contributor agreement - see http://www.ehcache.org/community/contribute.html

Also, could you raise an issue so that this commit can be linked to it.
And expect a comment (soon) on the strategy we have in place for fixing issues that apply to multiple branches, as is the case with yours here.

**Comment by ljacomet** [comment]
Regarding the bug fixing approach - have a look at https://github.com/ehcache/ehcache3/wiki/dev.git#initiate-a-pull-request

**Comment by zhanhb** [comment]
I agree . The source I committed is under no license, You can make any change on it.

**Comment by zhanhb** [comment]
Maybe the code should be
```java
super(referent, q);
if(referent == null) throw new NullPointerException();
hashCode = System.identityHashCode(referent);
```

**Pull request closed without merging**
