### PR TITLE
Including pom.xml and pom.properties in all published jars

### PR DESCRIPTION
**Pull request by akomakom**
Including maven metadata (pom.xml/pom.properties) in ehcache-common.jar only.  (primarily for internal use).

### CODE REVIEW

**Comment by akomakom** [comment]
This is the best way I found, and I made the assumption that this should only be done in one jar.  This could probably be abstracted to be done globally if needed.

**Comment by henri-tremblay** [comment]
I'm curious. You want to use it for what?

**Comment by GaryWKeim** [comment]
So you can crack it open and see useful information about the artifact. I'd also want, somewhere, the location of the repo it was born from. In the olden days it was quite a task to determine from where some artifact came.

**Comment by akomakom** [comment]
It's still quite a task... 

Answer: This change will allow the escrow plugin to identify it as an internal jar and then map it to where it came from.  I can discuss internal details in another channel if you're interested.

**Comment by henri-tremblay** [comment]
Ok. Thanks. I'm looking if we can make something simpler.

**Comment by akomakom** [comment]
Discussed with @ljacomet , I may be moving this to EhDeploy so it applies to all artifacts.

**Comment by akomakom** [comment]
Made a separate plugin, pom.* is now in all jars.

**Comment by akomakom** [comment]
I updated the maven plugin with new mappings so it should be ready once this is merged.

**Pull request merged**
