### PR TITLE
Add a CONTRIBUTING page to the repository

### PR DESCRIPTION
**Pull request by ljacomet**
This enables a link to appear in the GitHub UI when creating an issue
or a pull request linking to this content.

### CODE REVIEW

**Comment by ljacomet** [comment]
Once merged, the plan would be to include this file on the wiki page instead of hosting a copy of it.

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
test this please

**Comment by AbfrmBlr** [comment]
test this please

**Comment by ljacomet** [comment]
test this please

**Pull request merged**
