### PR TITLE
Return the real response from StateRepositoryMessages (close #2120)

### LINKED ISSUE #2120: ClassCastException on PUT_IF_ABSENT reponse after failover
PUT_IF_ABSENT should return a `MapValue` object in response. However, the message tracker currently records a `Success` which causes a `ClassCastException` on the client.

Running `BasicClusteredCacheOpsReplicationMultiThreadedTest` and looking at the output if a good way to reproduce it.

### PR DESCRIPTION
**Pull request by henri-tremblay**
The PR should be 3.4 compatible.

Two things I noticed that I would like advice on:
* Comment "Reaching here means a lifecycle or sync operation failed" is talking about lifecycle. But no lifecycle message is handled. Only sync messages
* PassiveReplication messages are logging errors and sync messages are throwing an exception. It feels odd. Is that normal?

### CODE REVIEW

**Comment by ljacomet** [comment]
@henri-tremblay the comment is most likely a left over when doing the single entity -> multi entity split a while ago.

With regards to exceptions, I believe the logic is that killing a passive while it is syncing makes sense since letting him move forward means having an invalid content. While a transient failure during message passing is ok as we expect a later mutation to still install the proper chain. Remember that we have single clustered tier entity -> segmented off heap maps -> multiple user keys can end up in the same key.

**Comment by ljacomet** [comment]
test this please

**Comment by henri-tremblay** [comment]
Ok. The comment about the lifecycle is now removed

**Comment by ljacomet** [comment]
Again that duplicate test failure

**Comment by henri-tremblay** [comment]
timeout increased to see how it goes

**Comment by henri-tremblay** [comment]
Can `BasicClusteredCacheOpsReplicationMultiThreadedTest.testClear` be longer than 3 minutes? I see nothing in the log telling that something went wrong.

**Comment by henri-tremblay** [comment]
Seeing the build history, it smells like something is wrong.

**Pull request merged**
