### PR TITLE
Spike : move conf before event

### PR DESCRIPTION
**Pull request by anthonydahanne**

### CODE REVIEW

**Comment by anthonydahanne** [comment]
here's why (I haven't finished testing it though,I just sent the PR to test if it broke some existing tests) : when you remove a cache from CM, if one of the listeners uses the configuration to trigger a notification, it could send a wrong notification.
Currently, if you remove a cache, your listeners still see the removed cache in the configuration object.
With that change, the listeners will see the updated the configuration (without the cache that was just removed)

**Comment by henri-tremblay** [comment]
The build failed on my flaky test. I will need to revisit it. @anthonydahanne I understand. But I would like a test to showcase it. Also, shouldn't it be done right after the `cacheHolder.retrieve`? And finally, but this is probably a question to @ljacomet. Do we need coherence (so synchronization) between what's in the `caches` and `configuration`?

**Comment by ljacomet** [comment]
This needs to be daggy fixed to 3.2, 3.3 and master

**Comment by anthonydahanne** [comment]
see #2011 #2012 #2013

**Pull request closed without merging**
