### PR TITLE
Issue 1105: very basic concurrency strategy

### PR DESCRIPTION
**Pull request by lorban**

### CODE REVIEW

**Comment by ljacomet** [comment]
You have a merge in that history - pretty sure that's not what you wanted.

**Comment by lorban** [comment]
I can't even explain how that merge ended up in there.

**Comment by AbfrmBlr** [comment]
I think we should try to differentiate between reads and mutations in concurrency startegy so that reads are not blocked on mutations which typically require passive replication (and FRS), making them slow.
If we do that I think we can get some advantage in read perf when we have passives and considerable mutations being done on cache.
I think we can do some perf tests to assert if moving reads to a different queue would really help.

**Comment by ljacomet** [comment]
@AbfrmBlr Created #1178 following your suggestion
@lorban looks good to me once rebased

**Comment by ljacomet** [comment]
Merged command line after a rebase

**Pull request closed without merging**
