### PR TITLE
Upgrade dependencies versions

### PR DESCRIPTION
**Pull request by anthonydahanne**

### CODE REVIEW

**Comment by ljacomet** [comment]
I have filed #1647 for this work, which depends on terracotta-oss/terracotta-platform#196 and started on it so closing this

**Comment by ljacomet** [comment]
This is incomplete and will not work. All `<service ...>` tags need to have their `id` attribute removed.

**Comment by anthonydahanne** [comment]
test this please
latest platform jars were not uploaded yet

**Comment by anthonydahanne** [comment]
This PR upgrades platform, and other terracotta server dependencies.
The tests are passing, [offheap resource using extended config](https://github.com/Terracotta-OSS/terracotta-platform/pull/198) can be added on top.

**Pull request merged**
