### PR TITLE
Use a local variable to calculate delta

### PR DESCRIPTION
**Pull request by henri-tremblay**
A put is about 20% faster with this code.

### CODE REVIEW

**Comment by chrisdennis** [comment]
I assume the reasoning on the performance improvement is that we're moving to a single update of the size for each operation rather than multiple updates right?

**Comment by henri-tremblay** [comment]
Yes. But actually, even with a byteSized=false, it is faster. So my line of thoughts is that it makes the JIT happier. But I can dig into the assembly to get confirmation.

**Comment by henri-tremblay** [comment]
test this please

**Comment by henri-tremblay** [comment]
Build failed because of TickingTimeSourceTest that is in fact flaky. PR #2432 should fix that.

**Pull request merged**
