### PR TITLE
Cleaning up unused MNM events

### PR DESCRIPTION
**Pull request by mathieucarbou**
@henri-tremblay @anthonydahanne @ljacomet : this is all the stuff that I think we do not need anymore since we can just stick with the raw voltron events to do the same thing.

__IMPORTANT__: We need to check in other projects first before merging that! I've just created this PR to show the work that has to be done

### CODE REVIEW

**Comment by ljacomet** [comment]
@mathieucarbou One important point: if we merge this in the 3.4.x line, does it break when mixed with 3.4.0 either on the client or the server?

**Comment by henri-tremblay** [comment]
test this please

**Comment by mathieucarbou** [comment]
@ljacomet @anthonydahanne @henri-tremblay : build pass. Can we merged and release so that we can integrate onto downstream projects ?
thanks!

**Comment by mathieucarbou** [comment]
@anthonydahanne @ljacomet @henri-tremblay : FYI please do not merge, I am still testing downstream projects and even if IT tests pass, when I test manually, things are not working in the UI...

**Comment by mathieucarbou** [comment]
UPDATE: forget it, issues was caused by firefox. It is working.

**Comment by mathieucarbou** [comment]
test this please

unreliable test:

```
Test Result (1 failure  / +1)
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationMultiThreadedTest.testClear[consistency=STRONG]
```

**Comment by mathieucarbou** [comment]
@ljacomet @chrisdennis @anthonydahanne @henri-tremblay : as seen with @chrisdennis , I will reopen this PR to be based on @henri-tremblay 's commit (https://github.com/ehcache/ehcache3/pull/2102/commits) and merge on master to to the proprer daggy fix

**Pull request closed without merging**
