### PR TITLE
Adding nexus staging plugin

### PR DESCRIPTION
**Pull request by akomakom**
Allows jobs to add "closeRepository" or "closeAndPromoteRepository" to the task list.

https://github.com/Codearte/gradle-nexus-staging-plugin/

### CODE REVIEW

**Comment by akomakom** [comment]
@ljacomet ping

**Comment by ljacomet** [comment]
@akomakom before merging this, could we make sure `closeAndPromoteRepository` is disabled? I do not want a release build just yet to be synced to maven central without some checks before.

**Comment by akomakom** [comment]
@ljacomet I could add some code that will raise an error if closeAndPromoteRepository is on the task list - aside from that there is nothing in the plugin config to disable it. 

Either way, the ony time closeAndPromoteRepository would be used is when it is explicitly passed on the command line, and only on hosts that have the credentials configured.

**Comment by ljacomet** [comment]
Some mess up with the rebase here - there is a not needed merge commit

**Comment by akomakom** [comment]
Yup fighting with git on this one

**Comment by akomakom** [comment]
... I guess there is always --force.

Anyway, I think that this plugin doesn't work with JDK1.6 anymore, so this may be throwaway.

**Comment by albinsuresh** [comment]
Can't this be closed then?

**Comment by akomakom** [comment]
Closing, I'll revisit this down the line.

**Comment by akomakom** [comment]
@ljacomet do we still want to do this?  Now that ehcache3 requires JDK8, this plugin would work.  I also disabled auto promote on my branch.  I'll open a new one if this is useful.

**Pull request closed without merging**
