### PR TITLE
Issue #965 Rename CacheStore to TieringStore

### PR DESCRIPTION
**Pull request by ljacomet**
* Rename CacheStoreProviderFactory to TieringStoreProviderFactory
* Rename relevant test classes

### CODE REVIEW

**Comment by ljacomet** [comment]
@lorban Review at will 😉

**Comment by lorban** [comment]
In need of rebasing

**Comment by ljacomet** [comment]
Done

**Comment by lorban** [comment]
Looks like you forgot to rename `CacheStoreConfiguration`

**Comment by ljacomet** [comment]
Indeed. Also realised that `TieredStore` was much better than `TieringStore` so adapted everything to use that new name.

**Pull request merged**
