### PR TITLE
Bump terracotta-core 5.4.0-pre20

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

**Comment by myronkscott** [comment]
you probably need a platform release first.

**Comment by henri-tremblay** [comment]
@myronkscott Which platform? We are already at 5.4.0-pre21

**Comment by myronkscott** [comment]
https://github.com/Terracotta-OSS/terracotta-platform needs to be moved to tc-core 5.4.0-pre20 and released first.

**Comment by henri-tremblay** [comment]
Was done by #2280

**Pull request closed without merging**
