### PR TITLE
It is the class, not the class name that is passed #1960

### PR DESCRIPTION
**Pull request by jdsandifer**
Changed _class name_ to _class_ on line 41 per #1960.

### CODE REVIEW

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by ljacomet** [comment]
Hi @jdsandifer, thank you very much for your interest in contributing to the project! Please read about submitting contributions here: http://www.ehcache.org/community/contribute.html and confirm in a reply comment that you agree to the grant statement under the heading "Agreement and Grant of Copyright"

**Comment by ljacomet** [comment]
Hi @jdsandifer,

Bump for the explicit grant statement as I am currently working on composing a global PR for all aspects of #1960 and would like to include this commit as well.

**Comment by jdsandifer** [comment]
I agree to the grant statement.

Is there somewhere I can do that globally? I've done it like three times
already...

- J.D.

**Comment by ljacomet** [comment]
Sure, you can sign a contributor agreement which will then cover small and large contributions. See the [contributing section](http://www.ehcache.org/community/contribute.html) on the website.

I should have thought of proposing it since you had a number of small patches proposed. Another way would have been to effectively create a single PR for the different commits.

Anyway, thanks again for your interest and help in making the documentation better.

**Comment by ljacomet** [comment]
Commit included in #2035 and #2036

**Pull request closed without merging**
