### PR TITLE
Clarify a serializers-copiers sentence #1960

### PR DESCRIPTION
**Pull request by jdsandifer**
Edited line 88 for clarity.

### CODE REVIEW

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by ljacomet** [comment]
Hi @jdsandifer, thank you very much for your interest in contributing to the project! Please read about submitting contributions here: http://www.ehcache.org/community/contribute.html and confirm in a reply comment that you agree to the grant statement under the heading "Agreement and Grant of Copyright"

**Comment by jdsandifer** [comment]
I agree to the grant statement.

**Comment by ljacomet** [comment]
Thanks, note that we will most likely cherry-pick this commit and make it part of a larger upcoming documentation update. When that happens, I'll point you to it and close this. As usual with git, the cherry-picked commit will still have proper ownership.

**Comment by jdsandifer** [comment]
Got it.

**Comment by ljacomet** [comment]
Commit included in #2035 and #2036

**Pull request closed without merging**
