### PR TITLE
Closes #1476 Doc improvements around XML configuration

### LINKED ISSUE #1476: Ehcache Javadoc unclear
When writing:

```
    cacheManager = CacheManagerBuilder.newCacheManager(new XmlConfiguration(config));
```

I do not know if I need to also call:

```
    cacheManager.init();
```

Because the Javadoc of `CacheManagerBuilder.newCacheManager()` is unclear about that:

```
  /**
   * Creates a new {@link CacheManager} based on the provided configuration
   *
   * @param configuration the configuration to use
   * @return a {@code CacheManager}
   */
  public static CacheManager newCacheManager(final Configuration configuration) {
    return new EhcacheManager(configuration);
  }
```

I think it should tell in which state the cache manager is returned.

### PR DESCRIPTION
**Pull request by albinsuresh**

### CODE REVIEW

**Comment by albinsuresh** [comment]
test this please

**Comment by ljacomet** [comment]
What bothers me about the previous build failure is that it happened in a test I supposedly fixed in #1602

**Comment by ljacomet** [comment]
Just realised one thing: this needs to be done as a daggy fix against `release/3.1` and `master`

**Comment by albinsuresh** [comment]
Replaced with #1621 and #1622

**Pull request closed without merging**
