### PR TITLE
Close #1575: management calls on server entities to configure stat collector

### LINKED ISSUE #1575: Do not auto-start collecting server entity stats
Instead, wait for a management call from TMC.

- [x] Requires: Terracotta-OSS/terracotta-platform#178 (=> PR Terracotta-OSS/terracotta-platform#182)
- [x] Remove management calls from `Management` and update the tests

### PR DESCRIPTION
**Pull request by mathieucarbou**
Also, upgraded Ehcache versions.

__Depends__ on Terracotta-OSS/terracotta-platform#182 (and a __5.0.11.beta2__ release of tc-platform)

### CODE REVIEW

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test thi please

**Comment by mathieucarbou** [comment]
test this please

**Comment by anthonydahanne** [comment]
test this please
an integration test (HA) failed in JDK7

**Comment by mathieucarbou** [comment]
test this please

**Pull request merged**
