### PR TITLE
Upgrade to new tc-platform 5.3.0-pre9 and new tc-core 5.3.0-pre7

### PR DESCRIPTION
**Pull request by mathieucarbou**

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@ljacomet : the build failed because of test failures not caused by our change in tc-platform... Could it be a bug with the new voltron release ?

```
	Test Result (2 failures / +2)
org.ehcache.clustered.CacheManagerLifecycleEhcacheIntegrationTest.testMultipleClientsAutoCreatingCacheManager
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationTest.testCRUD[consistency=STRONG]
```

**Comment by mathieucarbou** [comment]
test this please

**Comment by ljacomet** [comment]
test this please

**Comment by mathieucarbou** [comment]
@ljacomet : now:

```
Test Result (1 failure / +1)
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationWithMultipleClientsTest.testCRUD[consistency=EVENTUAL]
```

So it means they are 3 random tests in Ehcache now ? Be careful... Ehcache is going to beat M&M 😛

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
oups! another one!

```
	Test Result (1 failure / ±0)
org.ehcache.clustered.replication.BasicLifeCyclePassiveReplicationTest.testDestroyLockEntity
```

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
failed again, this time:

```
Test Result (6 failures / +5)
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationMultiThreadedTest.testClear[consistency=EVENTUAL]
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationMultiThreadedTest.testCRUD[consistency=EVENTUAL]
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationMultiThreadedTest.testBulkOps[consistency=EVENTUAL]
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationMultiThreadedTest.testClear[consistency=STRONG]
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationMultiThreadedTest.testCRUD[consistency=STRONG]
org.ehcache.clustered.replication.BasicClusteredCacheOpsReplicationMultiThreadedTest.testBulkOps[consistency=STRONG]
```

**Comment by ljacomet** [comment]
There is clearly something wrong happening. Will try to have a deeper look.

**Comment by henri-tremblay** [comment]
test this please

**Comment by mathieucarbou** [comment]
I have updated the PR to get the new tc-core release with bugfixes.

**Comment by mathieucarbou** [comment]
test this please

**Comment by henri-tremblay** [comment]
There is now a module conflict. @mathieucarbou can you check?

A conflict was found between the following modules:
- org.terracotta:entity-server-api:1.3.0-pre3
- org.terracotta:entity-server-api:1.3.0-pre2

**Comment by mathieucarbou** [comment]
need to wait for a new tc-platform release and new tc-core release because of a version dependency bug in tc-core

**Comment by mathieucarbou** [comment]
test this please

**Comment by ljacomet** [comment]
Still seeing a test failure, so needs more investigations. However java 6 and 7 even have compilation failures!

**Comment by henri-tremblay** [comment]
test this please

**Comment by henri-tremblay** [comment]
Restarting just to make sure it is stable

**Comment by ljacomet** [comment]
test this please

**Pull request merged**
