### PR TITLE
Upgrade to Gradle 4.5.1

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

**Comment by henri-tremblay** [comment]
Rebased

**Comment by ljacomet** [comment]
4.6 has been released already 😉

**Comment by henri-tremblay** [comment]
Yes. Not my fault if you are slow merging my PRs :-P

**Comment by henri-tremblay** [comment]
test this please

**Comment by chrisdennis** [comment]
@ljacomet  I understood that 4.5.1 comes with lifetime support though, right?

**Comment by ljacomet** [comment]
@henri-tremblay Indeed, I need to work on better filtering notifications. Still getting them all which makes finding where I am mentioned hard, sorry about that.

@chrisdennis Well no idea who signed up for that 😛

**Pull request merged**
