### PR TITLE
fix #2641 JSR107 MBeans are registered again and again

### LINKED ISSUE #2641: CacheConfiguration and CacheStatistics MBeans are registered again and again
Following #1928, CacheConfiguration and CacheStatistics MBeans are registered again for each call to `Caching.getCachingProvider().getCacheManager().getCacheNames()` (that is to `Eh107CacheManager.getCacheNames()`).

For example, the following code using the JSR107 api with Ehcache v3.7.1:
```java
MutableConfiguration conf = new MutableConfiguration();
conf.setManagementEnabled(true);
conf.setStatisticsEnabled(true);
Caching.getCachingProvider().getCacheManager().createCache("test", conf);
Caching.getCachingProvider().getCacheManager().getCacheNames();
Caching.getCachingProvider().getCacheManager().getCacheNames();
Caching.getCachingProvider().getCacheManager().getCacheNames();
```

gives the following logs:
```
15:32:57.025 [http-nio-8080-exec-2] INFO  org.ehcache.core.EhcacheManager - Cache 'test' created in EhcacheManager.
15:32:57.086 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.088 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.100 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.103 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.110 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.111 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.112 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheConfiguration,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
15:32:57.113 [http-nio-8080-exec-2] INFO  org.ehcache.jsr107.Eh107CacheManager - Registering Ehcache MBean javax.cache:type=CacheStatistics,CacheManager=urn.X-ehcache.jsr107-default-config,Cache=test
```

Registering MBeans again and again in `CacheManager.getCacheNames()` seems not needed and not efficient.
I suggest to check if MBeans are already registered, using `config.isManagementEnabled()` and `config.isStatisticsEnabled()` in `Eh107Cache`, before registering MBeans in `Eh107CacheManager.refreshAllCaches()`.

### PR DESCRIPTION
**Pull request by evernat**

### CODE REVIEW

**Comment by anthonydahanne** [comment]
thank you for your contribution !
We're almost there !
Can you please "fill out and mail the [Individual Contributor Agreement](https://confluence.terracotta.org/download/attachments/27918462/Terracotta%20Individual%20Contributor%20Agreement%20v3.pdf?version=1&modificationDate=1393442245216&api=v2) at contributors@terracotta.org."

Also, can you please add a test (preferably an integration test that'd test that you solved the issue - it could be mocking the mbean registration and asserting it was registered once, or it could be asserting the logs were displayed once, etc.)
thanks again !

**Comment by evernat** [comment]
@anthonydahanne 
I have just sent the contributor agreement.
About test, I am not a fan of mocking a mbean server.

**Review by SLionB — APPROVED** [review]

**Review by SLionB — APPROVED** [review]

**Review by cosmin-ronin — APPROVED** [review]

**Review by linghengqian — APPROVED** [review]

**Comment by linghengqian** [comment]
@evernat Can you deal with the merge branch conflict?

**Comment by chrisdennis** [comment]
This is replaced by #2996 which fixes the same symptoms but addresses the real root issue more directly. Review and feedback on that PR is welcome, and my apologies for the delay in looking at this.

**Pull request closed without merging**
