### PR TITLE
Bump dependencies to the latest Terracotta release

### PR DESCRIPTION
**Pull request by ljacomet**
This will allow to use the Entity creation exception possibility.

### CODE REVIEW

**Comment by ljacomet** [comment]
test this please

For some reason builds were stuck exploding the kit for the integration tests

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
Causing some test failures - will investigate

**Comment by AbfrmBlr** [comment]
test this please

**Comment by AbfrmBlr** [comment]
Will raise another PR with latest release.

**Pull request closed without merging**
