### PR TITLE
Update to latest tc platform and core

### PR DESCRIPTION
**Pull request by anthonydahanne**

### CODE REVIEW

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
@anthonydahanne : are yo usure you have rebased correctly on master ? 
I do not see from https://github.com/ehcache/ehcache3/network

**Comment by anthonydahanne** [comment]
@mathieucarbou yes it is based on master, please refresh the network view, sometimes github serves cached version...

**Comment by anthonydahanne** [comment]
test this please

**Comment by anthonydahanne** [comment]
test this please

**Comment by ljacomet** [comment]
Not cool - the PR build history shows 2 jobs that were aborted - it does not say if this is because of human intervention or just plain timeout of the job. Then the one passing has a test error which was never seen before and is an interrupted exception in the platform layer. For me, this means investigations before merging.

**Comment by ljacomet** [comment]
And indeed now we have PRs #1375 and #1381 failing on the same issue. I am going to open a PR reverting this merge. AFAICT the latest platform has a bug that Ehcache makes visible.

**Comment by mathieucarbou** [comment]
@ljacomet : when I merged, GitHub was showing that all checks have passed, as usual. There were no build issue at all or build running.

**Pull request merged**
