### PR TITLE
Fixes #1430 Final clean up of compilation warnings

### LINKED ISSUE #1430: Remove generics warnings
The build now prints all warnings. And there is a lot of them.

They should get fixed, in order to flush out any bugs they could hide but also to make the developer's life easier when chasing genuine javac failures. For the moment finding the failure amongst the warnings is a real challenge.

Note that some changes concern API classes and thus must be considered with care.

### PR DESCRIPTION
**Pull request by ljacomet**
This PR finalises the clean up of compilation warnings and turns warnings into errors in all module where it is possible.

### CODE REVIEW

**Comment by chrisdennis** [comment]
Is it clear how many of the `@SuppressWarnings` annotations are "required" and therefore inherently unfixable, and how many are fixable with time?  Would be good to have some way to distinguish these two classes so that fixing the fixable can be a trackable task.

**Comment by ljacomet** [comment]
I tried hard to fix all those I could. Example of unfixable: Mockito matchers `any(GenericClass.class)` which cannot be declared as a variable and thus force the suppress to happen at the method level.

Maybe such a categorisation should be made on prod source not test.

**Comment by chrisdennis** [comment]
Definitely makes more sense for the production usages.  Maybe we could use `//TODO` comments or something similar?

**Comment by henri-tremblay** [comment]
LGTM. I personally like to add a comment telling why a warning can't be fixed. Sometimes it's obvious though.

Then, I start to wonder if we shouldn't had a small mockito wrapper. Like (but I'm not happy with it yet)

```java
  public static class TT<T> {
  }

  public static <T> T typedMock(TT<T> typeWitness) {
    ParameterizedType type = (ParameterizedType) typeWitness.getClass().getGenericSuperclass();
    Type paramType = type.getActualTypeArguments()[0];
    if(paramType instanceof ParameterizedType) {
      paramType = ((ParameterizedType) paramType).getRawType();
    }
    return Mockito.mock((Class<T>) paramType);
  }
  
  @Test
  public void test() {
    List<String> l1 = typedMock(new TT<List<String>>() {});
  }
```

**Comment by ljacomet** [comment]
@henri-tremblay Yes, need to do one more pass on the suppressed warnings in prod code, will get to it tomorrow.
Regarding mockito, whenever possible I replace the `mock(Class)` call with an annotated field. I have the impression that your solution is overkill for tests, where the `@SuppressWarnings` is clear enough.

**Comment by henri-tremblay** [comment]
It's just that I'm afraid we will have a lot of `@SuppressWarning`. Both I agree the best way is to use `@Mock`.

A simpler way that adds a parameter but removes the anonymous inner class is:

```java
  public static class TT<T> {
  }

  public static <T> T typedMock(TT<T> typeWitness, Class<?> rawType) {
    return (T) Mockito.mock(rawType);
  }
  
  @Test
  public void test() {
    List<String> l1 = typedMock(new TT<List<String>>());
  }
```

**Pull request merged**
