### PR TITLE
Add update statistics

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

**Comment by henri-tremblay** [comment]
test this please

**Comment by mathieucarbou** [comment]
@henri-tremblay @ljacomet @lorban : good for me, but i'd like that one of you also look at it perhaps ?

**Comment by henri-tremblay** [comment]
I'm wondering something. So the changes also be applied to `EhcacheWithLoaderWriter`?

**Comment by mathieucarbou** [comment]
@henri-tremblay : needs to be rebased

**Comment by henri-tremblay** [comment]
Rebased

**Comment by mathieucarbou** [comment]
Test this please

**Comment by mathieucarbou** [comment]
Test this please

**Comment by mathieucarbou** [comment]
@henri-tremblay @chrisdennis @anthonydahanne @ljacomet : it seems there are several tests in ehcache that randomly fails and prevent this PR to build.

**Comment by henri-tremblay** [comment]
test this please

**Comment by henri-tremblay** [comment]
Test this please

**Pull request merged**
