### PR TITLE
Add calculated expiry to ValueHolder

### PR DESCRIPTION
**Pull request by tiparega**
For bug #2050: Expiry infinite when mixing onHeap and clustered Tiers

Use a custom Result to return ResolvedResult with expiry information.
Detect it and set the expirationTime on ValueHolder. Ugly, but it works.

### CODE REVIEW

**Comment by terracotta-org** [comment]
Can one of the admins verify this patch?

**Comment by henri-tremblay** [comment]
I will use part of your PR with heavy refactoring. Thanks for contributing! Can you please fill the contributing agreement? https://github.com/ehcache/ehcache3/blob/master/CONTRIBUTING.adoc#contributor-agreement

**Comment by ljacomet** [comment]
Hi @tiparega,

This contribution falls under the conditions described under the heading "Contributions which do require a full Contributor’s License Agreement (CLA)" here: http://www.ehcache.org/community/contribute.html

We very much appreciate your contribution, and request that you submit a signed agreement.

Thanks!

**Comment by tiparega** [comment]
Hello, I just sent it. Thanks for your work on this project.

**Comment by henri-tremblay** [comment]
Has unexpectedly closed. Replaced by #2064

**Comment by ljacomet** [comment]
@tiparega,

We have received your contributor agreement - thanks a lot for your interest in the project.

**Pull request closed without merging**
