### PR TITLE
Made management objects serializable and removed duplicate naming for…

### PR DESCRIPTION
**Pull request by mathieucarbou**
… stats

I had to update management model objects to make them properly deserializable, plus improved some little things like removing duplicate naming for stats and renamed PERCENT to RATIO.

Depends on https://github.com/Terracotta-OSS/terracotta-management/pull/19

@anthonydahanne : once PR #19 will be reviewed / merged / released, you'll be able to review and merge this one :-)

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@chrisdennis : I do not know if it is normal but I couldn't set @anthonydahanne as the assignee ;-)

**Comment by mathieucarbou** [comment]
@anthonydahanne : this requires this PR also: https://github.com/Terracotta-OSS/terracotta-management/pull/20

**Comment by mathieucarbou** [comment]
test this please

**Comment by anthonydahanne** [comment]
LGTM

**Pull request merged**
