### PR TITLE
Give access to the ServiceLocator for power users

### PR DESCRIPTION
**Pull request by henri-tremblay**

### CODE REVIEW

**Comment by anthonydahanne** [comment]
@henri-tremblay  can you please add an example of usage of this change ? thanks

**Comment by henri-tremblay** [comment]
My favorite example would be
```
StatisticsService stats = ((InternalCacheManager) cacheManager)
    .getServiceProvider().getService(StatisticsService.class);
```
It is currently impossible to retrieve the `StatisticsService` when using JSR107 to configure the `CacheManager`.

**Comment by anthonydahanne** [comment]
got it, thanks !

**Comment by chrisdennis** [comment]
Isn't the real need here for a public statistics API? Not sure what the value is in having this as a stop-gap? I'd rather just solve the problem properly and leave the service locator as hidden as it currently is.  Doesn't this essentially risk having more users assuming they can rely on the internal details of classes to no change?  Not sure what upside it has as it stands.

**Comment by henri-tremblay** [comment]
Yes, a statistics API is a must. But having useful access to internal features with all the required red flags is a nice way to test and incubate features.

**Pull request closed without merging**
