### PR TITLE
Issue 2456 feature branch merge - Clustered loader writer implementation

### PR DESCRIPTION
**Pull request by AbfrmBlr**
Pull request to merge feature branch  of clustered loader writer implmentation

### CODE REVIEW

**Comment by henri-tremblay** [comment]
That is serious stuff :-) I'll look at it as soon as I can. However, it seems it needs a rebase.

**Comment by AbfrmBlr** [comment]
This does not need a rebase, this feature has followed the model of feature branching. So only merge conflicts will be resovled. The review has already been done and this needs to go today. See https://github.com/AbfrmBlr/ehcache3/pull/3

**Comment by AbfrmBlr** [comment]
test this please

**Comment by AbfrmBlr** [comment]
rebased

**Comment by AbfrmBlr** [comment]
test this please

**Comment by ramsai1729** [comment]
test this please

**Comment by AbfrmBlr** [comment]
test this please

**Comment by AbfrmBlr** [comment]
rebased

**Pull request merged**
