### PR TITLE
Issue #569 - Declared services in org.ehcache.spi.service.ServiceFact…

### PR DESCRIPTION
**Pull request by mathieucarbou**
@ljacomet : This is a PR which includes a unit test to be able to reproduce issue #569

### CODE REVIEW

**Comment by mathieucarbou** [comment]
@ljacomet : I just added a fix to ServiceLocator class, but I really do not know if it is the right way to fix this.

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
please test this

**Comment by mathieucarbou** [comment]
test this please

**Comment by mathieucarbou** [comment]
test this please

**Comment by ljacomet** [comment]
Replaced by PR #573

**Pull request closed without merging**
