### PR TITLE
[3.5] Remove APPEND since it will probably stay unused forever

### PR DESCRIPTION
**Pull request by henri-tremblay**
In fact, can probably be 3.4 since it removes unused code.

### CODE REVIEW

**Comment by henri-tremblay** [comment]
That will mean to have only two `PutOutcome`: `PUT` and `FAILURE`. I am fine with that. However, you will have to discuss with @ljacomet about it.

**Comment by henri-tremblay** [comment]
Ok. So, right now we need PUT, NOOP and FAILURE for 107 statistics. The failing test when not considering NOOP is `CacheMBStatisticsBeanTest.testExpiryOnCreation`.

**Comment by henri-tremblay** [comment]
Might be replaced by #2129

**Comment by ljacomet** [comment]
Closing this as we will go with #2156

**Pull request closed without merging**
