### PR TITLE
Issue #512 Use gradle daemon

### PR DESCRIPTION
**Pull request by ljacomet**
* Bump gradle to version 2.6
* Bump shadow plugin to 1.2.2
* Configure gradle daemon with max memory and perm gen memory

### CODE REVIEW

**Comment by chrisdennis** [comment]
The Gradle documentation doesn't call it out explicitly, but it does always refer to enabling the daemon in an environment, not in a project.  I'd rather just add some documentation to the developer wiki about how to get around it rather than enabling the daemon in the project itself.  That way we also don't have to worry about remembering to disable it in the CI system(s).

https://docs.gradle.org/current/userguide/gradle_daemon.html

**Comment by ljacomet** [comment]
Good point indeed.

So of the two properties:
````
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx512m -XX:MaxPermSize=128m 
````
I remove the first one, keep the second one and add a wiki section documenting that you need to either use the daemon or apply `GRADLE_OPTS`.
Better?

**Comment by chrisdennis** [comment]
Yes, I think that makes sense.

**Comment by ljacomet** [comment]
Udpated PR and find below the proposed [wiki](https://github.com/ehcache/ehcache3/wiki) addition:

> ## Developer be welcome
> ...
>
> ## Building Ehcache 3
> The build system is [Gradle](http://gradle.org). Ehcache 3 is built by default using Java 1.6 and remains compatible with that version.
> The project is configured to use the [Gradle daemon](https://docs.gradle.org/current/userguide/gradle_daemon.html). Simply add a `gradle.properties` file in your `$HOME/.gradle/` folder with the following content:
> ````
> org.gradle.daemon=true
> ````
> If that is not an option, make sure you define the following environment variable:
> `GRADLE_OPTS=GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=128m"`
>
> ## How to contribute?
> ...

**Pull request merged**
