### PR TITLE
added asciidocs for ehcache3, spring, jsr107 example

### PR DESCRIPTION
**Pull request by gibsong**
I have added my asciidocs for the spring, jsr107, ehcache3 blog post.  Please let me know if I need to make any changes.

### CODE REVIEW

**Comment by ljacomet** [comment]
Irrelevant of the content, this makes me wonder where we want to store articles.

Here with the Ehcache code? or rather on the website itself?

I tend to favour the second option.
@chrisdennis @lorban @jhouserizer @cljohnso @AbfrmBlr wdyt?

**Comment by AbfrmBlr** [comment]
I thought all the blogs will go to http://blog.terracotta.org/, where some of them relevant to ehcache3 are present.
If not so, then I also vote for second option.

**Comment by gibsong** [comment]
Shoot, I though we had already discussed the location of the articles.  Originally, James asked me to put them in this location.  However, I have no problem moving them.  Please let me know what the final decision is so I can get famous for my first blog post.  Where are the website files stored?

**Comment by ljacomet** [comment]
General recommendation on writing asciidoc: go to a new line after each "." as it helps when reviewing / updating and tracking source changes.

**Comment by gibsong** [comment]
This request was closed and replaced with the following PR
https://github.com/gibsong/ehcache-jsr107-spring/pull/1

**Pull request closed without merging**
