### PR TITLE
Fix Issue 1853

### PR DESCRIPTION
**Pull request by satyen-chimulkar**

### CODE REVIEW

**Review by chrisdennis — CHANGES_REQUESTED** [review]
The product code changes look fine, but the test failures need addressing here.

**Review by chrisdennis — CHANGES_REQUESTED** [review]
Changes now look fine... but the commit structure is a little wrong.

69da1bf64564ec8b2acb860a48e6237f55ae7cd5 should be before the merges that integrate with `master` (and probably just be squashed in with the fix commit). Then we should ideally have just one merge commit (in the direction of your choice) that integrates the changes with `master`.

**Comment by satyen-chimulkar** [comment]
Closing PR to create a new PR with changes

**Comment by chrisdennis** [comment]
PRs are just a request to merge one branch in to another branch. There should be no need to close this in order to fix the commit graph. Just manipulate the graph locally, and then force push to your fork.

**Pull request closed without merging**
