### PR TITLE
Integration tests now use Galvan to run against the actual built kit

### PR DESCRIPTION
**Pull request by chrisdennis**
The thing I have most concern with here is the effect this has on test runtimes.

### CODE REVIEW

**Comment by chrisdennis** [comment]
I think this is failing because the cloudless machines don't have a valid toolchains.xml.  I'm going to make some changes so that this fails in a clearer way, and re-push.  Not sure what to do about the actual problem however.

**Comment by AbfrmBlr** [comment]
test this please

**Comment by ljacomet** [comment]
test this please

**Comment by ljacomet** [comment]
Now that this PR builds, what's next before merging @chrisdennis ?

**Comment by chrisdennis** [comment]
I have one more thing to play with to see if I can reduce test runtimes still further.  I will run that experiment today... other than that nothing.

**Comment by chrisdennis** [comment]
@ljacomet I think this is as good as we can get runtime wise for the moment.  The remaining test time is dominated by the election period when the servers first start up.  We can look in to filing an issue about this in Terracotta-OSS/galvan but for now this can be considered eligible for merging.

**Comment by ljacomet** [comment]
Once rebased, good to go

**Pull request merged**
