### PR TITLE
(docs): fixed small errors

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Comment by chrisdennis** [comment]
I'm happy to merge these fixes but the commit graph here is a little confused/complicated. With these kinds of changes there are really three ways you can structure them.

1. A sequence of simple commits rebased against the HEAD of master.
2. One or more daggy fixes (https://wiki.monotone.ca/DaggyFixes/) hanging from the source of the bug, with one PR each.
3. A branch from the HEAD of master with one or more daggy fixes merged in to it and then PR'ed as a single unit.

I would suggest that 1 is sufficient in this case unless you want to follow 2 or 3 out of curiosity (they are required for code bug fixes).

**Comment by 0xflotus** [comment]
I'm not really sure what to do?

**Comment by chrisdennis** [comment]
No worries. Let assume you want to go with the first approach. Working from your current branch you can see that we have a more complex graph of commits than we need:
```
ehcache3 % git log --graph master.. 
*   commit c1d94aa564f5cb8c31921d4367903bca787ca074 (HEAD -> patch-1, origin/patch-1)
|\  Merge: cdd9afe77 b3309185c
| | Author: 0xflotus <0xflotus@gmail.com>
| | Date:   Sun Apr 26 23:53:51 2020 +0200
| | 
*   commit c1d94aa564f5cb8c31921d4367903bca787ca074 (HEAD -> patch-1, origin/patch-1)
|\  Merge: cdd9afe77 b3309185c
| | Author: 0xflotus <0xflotus@gmail.com>
| | Date:   Sun Apr 26 23:53:51 2020 +0200
| | 
| |     Merge pull request #2 from 0xflotus/patch-2
| |     
| |     Update tiering.adoc
| | 
| * commit b3309185c4efa830bd5470796fa99027be374266
|   Author: 0xflotus <0xflotus@gmail.com>
|   Date:   Sun Apr 26 23:53:31 2020 +0200
|   
|       Update tiering.adoc
|   
*   commit cdd9afe773669123c40dd863e70a7619cc051b8f
|\  Merge: fe45c7320 072ec49d0
| | Author: 0xflotus <0xflotus@gmail.com>
| | Date:   Sun Apr 26 23:51:18 2020 +0200
| | 
| |     Merge pull request #1 from 0xflotus/patch-2
| |     
| |     Update osgi.adoc
| | 
| * commit 072ec49d01b931120efa694327cd84ebfa9bc5dd
|   Author: 0xflotus <0xflotus@gmail.com>
|   Date:   Sun Apr 26 23:50:55 2020 +0200
|   
|       Update osgi.adoc
| 
* commit fe45c7320ae4f958448b967aa6646da10edfcb90
  Author: 0xflotus <0xflotus@gmail.com>
  Date:   Sun Apr 26 23:45:04 2020 +0200
  
      Update caching-terms.adoc
```
To get these commits as single sequence running from the HEAD of master we simply have to:
```
ehcache3 % git rebase master              
First, rewinding head to replay your work on top of it...
Applying: Update caching-terms.adoc
Applying: Update osgi.adoc
Applying: Update tiering.adoc
```
This will replay your commits on top of master, and because rebase will by default drop all merge commits it will flatten everything in to a nice sequence. This leaves us with:
```
ehcache3 % git log --graph master..       
* commit c65f3a7c87e0ac3c2e35a97edfe646b5bd15ac85 (HEAD -> patch-1)
| Author: 0xflotus <0xflotus@gmail.com>
| Date:   Sun Apr 26 23:53:31 2020 +0200
| 
|     Update tiering.adoc
| 
* commit f618b0702e75a253544fa3ce89251cba6496ec42
| Author: 0xflotus <0xflotus@gmail.com>
| Date:   Sun Apr 26 23:50:55 2020 +0200
| 
|     Update osgi.adoc
| 
* commit f7308d49d85d62049c67b642902d26f5516181c4
  Author: 0xflotus <0xflotus@gmail.com>
  Date:   Sun Apr 26 23:45:04 2020 +0200
  
      Update caching-terms.adoc
```
Assuming everything looks right after this you can then just force push these commits to your remote and the PR will get updated automatically:
```
ehcache3 % git push -f
```
Hope this helps!

Chris

**Comment by 0xflotus** [comment]
@chrisdennis thanks for the hint. Is it ok so?

**Comment by chrisdennis** [comment]
I took the liberty of rebasing this against current master (it had moved since you last fetched). I will merge once CI has completed.

**Pull request merged**
