### PR TITLE
Proper else clause invoke #1482

### PR DESCRIPTION
**Pull request by AbfrmBlr**

### CODE REVIEW

**Comment by ljacomet** [comment]
Killed build given comment above

**Comment by AbfrmBlr** [comment]
@ljacomet what else we can do? Can we throw exception to bring down the server. The only way on passive entity is to log the exception. The only other stuff you can do is to log at other places, but that does not change anything in design, other than refactoring the code.

**Comment by AbfrmBlr** [comment]
@ljacomet , ca we discuss this ?

**Comment by ljacomet** [comment]
Fix will be part of #1657

**Pull request closed without merging**
